### ISSUE TITLE
feat: add starkscan link to token activity and collection activity tables

### ISSUE THREAD

**Issue by YohanTz** [ArkProjectNFTs/ark-market#167]
### Describe the feature you'd like to request

Add starkscan link to token activity and collection activity tables, in `desktop-collection-activity.tsx` and `desktop-portfolio-activity.tsx`. The necessary data is available in the props of the components.

### Describe the solution you'd like to see

Add links that redirects to starkscan in the token / collection activity tables

**Comment by stephanniegb** [comment]
Hey @YohanTz, I would like to work on this.

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hi! My name is Luis Sanchez, and I’m a Frontend Developer with 3 years of experience, specializing in TypeScript and React. I have extensive experience working with Next.js and building dynamic, responsive UIs. i'm gonna be glad to contribute

### How I plan on tackling this issue
I will start by identifying the exact location in the desktop-collection-activity.tsx and desktop-portfolio-activity.tsx components where the token and collection activity tables are rendered. I’ll then utilize the data available in the props to construct Starkscan links, ensuring that the URLs are dynamically generated based on the token and collection IDs. I’ll add these links to the respective table cells, making sure they follow the design and user experience guidelines. Finally, I’ll test the links thoroughly to ensure they navigate correctly to the Starkscan pages.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a software developer with 6 years experience in building applications

### How I plan on tackling this issue
I would add the starkscan link to the token and collection activity tables and open the link in a new tab
ETA- 24 hours

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
GM, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo language. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
Hi @YohanTz, my approach: 
- In both desktop-collection-activity.tsx and desktop-portfolio-activity.tsx, utilize the data available in the props to generate URLs that point to StarkScan.

- The URL format for StarkScan should be determined based on the token or collection details (like token ID, collection address, etc.).

- Each row in the activity tables will contain a clickable link that redirects users to the respective StarkScan page, allowing for easy tracking of token/collection activity.

- Ensure the links are only visible for desktop layouts, following the current table structure.

- This addition will enhance user experience by providing direct access to StarkScan for more detailed insights into their assets.

### Tasks:
- [ ] Add links in both the files

## ETA: 6 Hours

**Comment by omsant02** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
the last column in both activity tables, which previously had an empty ExternalLink, is the ideal place to add the Starkscan link,

the necessary data for implementing this feature is already available in the props of the components

the transaction hash, available in the activity data (activity.transaction_hash), could be used to construct the Starkscan URL

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I'm Benjamin, a full-stack JavaScript developer, and I'm ready to add Starkscan links to the token and collection activity tables. With 18 contributions at OnlyDust under my belt, I’m ready to tackle this feature.

### How I plan on tackling this issue
First, I’ll dive into the desktop-collection-activity.tsx and desktop-portfolio-activity.tsx files to get a clear picture of how the activity tables are set up. I’ll use the data we already have in the component props to create links that lead to Starkscan for both token and collection activities.

My goal is to make these links easy to spot and use, so users can quickly access detailed information about their activities. I’ll also make sure to test everything to ensure the links work smoothly and fit well within the existing layout.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
**UI: Add Starkscan Links to Token and Collection Activity Tables**

Hello Starknet Quest team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of the issue related to **Add Starkscan Link to Token and Collection Activity Tables**. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
#### Implementation Plan

**STEP 1:** Review the existing components.  
*Description:* I will analyze the `desktop-collection-activity.tsx` and `desktop-portfolio-activity.tsx` files to understand the current structure and how data is passed through props.

**STEP 2:** Identify the necessary data for links.  
*Description:* I will identify the specific data available in the component props that can be used to create the Starkscan links for both token and collection activities.

**STEP 3:** Implement the links.  
*Description:* I will add links to Starkscan in the token and collection activity tables, ensuring that the links redirect users to the correct pages based on the respective activity.

**STEP 4:** Testing.  
*Description:* I will perform testing to ensure that the links function correctly and direct users to the appropriate Starkscan pages.

### Goal

The goal is to enhance user experience by providing easy access to Starkscan for token and collection activities directly from the activity tables.

I look forward to your feedback on my approach!

**Comment by kwiss** [comment]
@stephanniegb i assigned you on it

**Comment by stephanniegb** [comment]
@kwiss noted
